# These are supported funding model platforms
github: ioniacob
patreon: ioniacob
open_collective: ioniacob
ko_fi: ioniacob
tidelift: ioniacob
community_bridge: ioniacob
liberapay: ioniacob
issuehunt: ioniacob
lfx_crowdfunding: ioniacob
polar: ioniacob
buy_me_a_coffee: ioniacob
thanks_dev: ioniacob
custom:
  - https://github.com/sponsors/ioniacob
  - https://patreon.com/ioniacob
  - https://ko-fi.com/ioniacob
  - https://buymeacoffee.com/ioniacob
